### ISSUE TITLE
读取流方式PDF页面数量正确，但是页面为空白

### ISSUE THREAD

**Issue by Ligenmt** [goSunadeod/vue-pdf.js-demo#5]
按照试例将 https://dluat.hscf.com/api/esm/v1/contractTemplates/load/c08def54aa40412b8b511406fc0271d2/0?access_token=ea19dc0de8801b389ed5099a2297161d&name=cehsi.pdf
改为我自己项目的url，能正常打开新页面，但是页面上的pdf都是空白页。

**Comment by goSunadeod** [comment]
https://www.jianshu.com/p/242525315bf6 这是博客底下有小伙伴遇到和你同样的问题，提过的链接，希望对你有所帮助

**Comment by Ligenmt** [comment]
谢谢！我又参考了很多博客，最后发现是后端返回流的问题，修改后端代码后解决了！

**Comment by Ligenmt** [comment]
经过验证，直接调Springboot后端接口显示正常，但是调用zuul网关来跳转到后端接口显示空白页，暂时还未找到原因。。。
